vim.cmd("set termguicolors")



require("user/packer")
-- require("plugins.neoformat")
-- require("packer_compiled.lua") this is autogenerated via packer
require("core/options")
require("core/colors")
require("core/autocmd")
require("core/keymaps")


require("user/neogit")
require("user/telescope") --needs live_grep config still
--require("user/neoformat")--see bugs in lua file


-- require("plugins/neoformat")
-- require('core/statusline')
-- require('plugins/nvim-tree')
-- require('plugins/indent-blankline')
-- require('plugins/nvim-cmp')
-- require('plugins/nvim-lspconfig')
-- require('plugins/nvim-treesitter')
-- require('plugins/alpha-nvim')



