require("core/options")
require("user/packer")
require("core/colors")
require("core/autocmd")
require("core/keymaps")

require("user/neogit")
require("user/devicons") -- NOTE: must be ahead of telescope
require("user/telescope") --needs live_grep config still
require("user/lsp")
require("user/neoformat")
require("user/cmp")
require("user/mason")
require("user/comment")
require("user/lualine")
require("user/treesitter")
require("user/whichkey")
require("user/markdown_preview")
require("user/vimwiki")
require("user/copilot")
